name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"]

  # 允許從 Actions 標籤頁面手動執行此工作流程
  workflow_dispatch:

# 設定 GITHUB_TOKEN 的權限，以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允許一個並發的部署，跳過正在運行和最新隊列之間的運行
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
